export const mapValueToGenre = (value: number): MovieGenre => GENRE_NUMERATION[value] as MovieGenre;

export enum MovieGenre {
	Action = 'Action',
	Adventure = 'Adventure',
	Animation = 'Animation',
	Comedy = 'Comedy',
	Crime = 'Crime',
	Documentary = 'Documentary',
	Drama = 'Drama',
	Family = 'Family',
	Fantasy = 'Fantasy',
	History = 'History',
	Horror = 'Horror',
	Music = 'Music',
	Mystery = 'Mystery',
	Romance = 'Romance',
	ScienceFiction = 'ScienceFiction',
	Thriller = 'Thriller',
	War = 'War',
	Western = 'Western',
}

export const GENRE_NUMERATION: Record<number, MovieGenre> = {
	[28]: MovieGenre.Action,
	[12]: MovieGenre.Adventure,
	[16]: MovieGenre.Animation,
	[35]: MovieGenre.Comedy,
	[80]: MovieGenre.Crime,
	[99]: MovieGenre.Documentary,
	[18]: MovieGenre.Drama,
	[10751]: MovieGenre.Family,
	[14]: MovieGenre.Fantasy,
	[36]: MovieGenre.History,
	[27]: MovieGenre.Horror,
	[10402]: MovieGenre.Music,
	[9648]: MovieGenre.Mystery,
	[10749]: MovieGenre.Romance,
	[878]: MovieGenre.ScienceFiction,
	[53]: MovieGenre.Thriller,
	[10752]: MovieGenre.War,
	[37]: MovieGenre.Western,
} as const;
